### ISSUE TITLE
something wrong ahout 4bit_rdn_x4.pt

### ISSUE THREAD

**Issue by yiyayiya557** [colorjam/PAMS#4]
ckpt = torch.load(f'{args.refine}') cannot load 4bit_rdn_x4.pt
maybe somethine wrong about it

> (pytorch110) robert@robert-Z390-GAMING-X:~/DeepLearning/ModelCompression/PAMS-master$  cd /home/robert/DeepLearning/ModelCompression/PAMS-master ; /usr/bin/env /home/robert/anaconda3/envs/pytorch110/bin/python /home/robert/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher 35723 -- /home/robert/DeepLearning/ModelCompression/PAMS-master/main.py --scale 4 --k_bits 4 --model RDN --data_test Set14 --save output/rdn_x4/8bit --dir_data /home/robert/Datasets/SuperResolutionData --test_only --refine ./pretrained/4bit_rdn_x4.pt --save_results 
Traceback (most recent call last):
  File "/home/robert/DeepLearning/ModelCompression/PAMS-master/main.py", line 255, in <module>
    main()
  File "/home/robert/DeepLearning/ModelCompression/PAMS-master/main.py", line 236, in main
    ckpt = torch.load("./pretrained/4bit_rdn_x4.pt")
  File "/home/robert/anaconda3/envs/pytorch110/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/robert/anaconda3/envs/pytorch110/lib/python3.7/site-packages/torch/serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 0 got 1

**Comment by SumanDeedwaniya** [comment]
@colorjam ....Can you check with this one as i am also facing the same issue. Seems like some uploading issue with the model.
